### ISSUE TITLE
Relative dependencies to elm-analyse

### ISSUE THREAD

**Issue by andys8** [antew/elm-lsp#1]
### Description

There are relative paths used in dependencies. This could be the cause for a problem with local installations of elm-analyse. It's just a guess, and I have to few information to recreate the issue consistently. If there is no drawback, it could make sense to remove relative paths anyway :)

### Change

This is the current dist output:

```js
var vscode_languageserver_1 = require("vscode-languageserver");
var fileLoadingPorts = __importStar(require("../node_modules/elm-analyse/ts/file-loading-ports"));
// import * as dependencies from '../node_modules/elm-analyse/ts/util/dependencies';
var dependencies = __importStar(require("../node_modules/elm-analyse/ts/util/dependencies"));
var Elm = require("../../node_modules/elm-analyse/dist/app/backend-elm.js").Elm;
```

This is output is without relative paths:

```js
var vscode_languageserver_1 = require("vscode-languageserver");
var fileLoadingPorts = __importStar(require("elm-analyse/ts/file-loading-ports"));
// import * as dependencies from 'elm-analyse/ts/util/dependencies';
var dependencies = __importStar(require("elm-analyse/ts/util/dependencies"));
var Elm = require("elm-analyse/dist/app/backend-elm.js").Elm;
```

The result compiles and runs:

```shell
$ tsc -p tsconfig.json
$ chmod +x dist/lib/index.js
$ ./dist/lib/index.js
There is no elm.json file in this directory. elm-lsp will only work in directories where such a file is located.```

**Comment by antew** [comment]
Released as [v1.0.2](https://github.com/antew/elm-lsp/tree/v1.0.2)

I think it not finding the `elm-analyse.json` may have another cause, but the package names look nicer in the code than the relative paths either way, so thank you!
