### ISSUE TITLE
Doesn't climb directories looking for `elm.json`

### ISSUE THREAD

**Issue by bengolds** [antew/elm-lsp#3]
This is so great -- thanks for putting this together.
Currently, it only seems to work if I'm my Vim `cwd` is the same as the directory with the `elm.json`. It'd be nice if it could recursively check parent directories for `elm.json`, that way I can work in subdirectories.

**Comment by antew** [comment]
That's a great idea, I should have some time in the next few days to work on it, thank you!

**Comment by antew** [comment]
Released as version v1.0.3, should be available on npm shortly!

**Comment by antew** [comment]
I checked tonight and it is available on npm, let me know if you notice any issues with it.

Cheers!

**Comment by bengolds** [comment]
Works great! Cheers, man.
